# Library Imports: 
- Make sure requirements.txt is installed before running this script.

In [1]:
import pandas as pd
import yfinance as yf

from datetime import date

# Preporcessing function are here:

In [2]:
def remove(x):
    """
    This function will strip the data column of the dataframe.
    """
    x = str(x)
    res = x.split(" ")[0]
    return res

# Calling Yahoo Finance API to get latest data of bitcoin
- To know more Click [here](https://finance.yahoo.com/quote/BTC-USD/)

In [3]:
btc = yf.Ticker("BTC-USD")  
btc = btc.history(period="max")  # we want the max data avialable 
btc.index = pd.to_datetime(btc.index)  # changing the index
btc.index = btc.index.to_series().apply(lambda x:remove(x))  # applying preprocessing function
btc.to_csv('BTC_USD.csv')  # saving the data in csv format
btc  # displaying the data.

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2014-09-17,465.864014,468.174011,452.421997,457.334015,21056800,0.0,0.0
2014-09-18,456.859985,456.859985,413.104004,424.440002,34483200,0.0,0.0
2014-09-19,424.102997,427.834991,384.532013,394.795990,37919700,0.0,0.0
2014-09-20,394.673004,423.295990,389.882996,408.903992,36863600,0.0,0.0
2014-09-21,408.084991,412.425995,393.181000,398.821014,26580100,0.0,0.0
...,...,...,...,...,...,...,...
2025-06-26,107375.070312,108305.546875,106666.351562,106960.000000,43891990613,0.0,0.0
2025-06-27,106954.921875,107772.468750,106449.992188,107088.429688,45353692675,0.0,0.0
2025-06-28,107090.546875,107567.882812,106883.976562,107327.703125,30037708335,0.0,0.0
2025-06-29,107327.820312,108526.304688,107230.109375,108385.570312,35534874438,0.0,0.0
2025-06-30,108380.781250,108786.710938,106794.960938,107777.492188,41317273600,0.0,0.0